### ISSUE TITLE
prepare_dataset issue

### ISSUE THREAD

**Issue by julianaamorim** [meddwl/psearch#21]
Hello, I have just installed psearch and all the env dependencies in conda. I downloaded the acetylcholinestarase (AChE) dataset to do a test and in the phase of preparing the dataset I came across the following error:

**Traceback (most recent call last):
  File "/home/juliana/anaconda3/envs/psearch/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/juliana/anaconda3/envs/psearch/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)Traceback (most recent call last):
  File "/home/juliana/anaconda3/envs/psearch/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/juliana/anaconda3/envs/psearch/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/juliana/anaconda3/envs/psearch/lib/python3.12/site-packages/psearch/prepare_dataset.py", line 61, in common
    create_db.main_params(dbout_fname=filenames[4],
  File "/home/juliana/anaconda3/envs/psearch/lib/python3.12/site-packages/psearch/scripts/create_db.py", line 156, in main_params
    for i, res in enumerate(p.imap_unordered(map_process_mol,
  File "/home/juliana/anaconda3/envs/psearch/lib/python3.12/multiprocessing/pool.py", line 451, in <genexpr>
    return (item for chunk in result for item in chunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/juliana/anaconda3/envs/psearch/lib/python3.12/multiprocessing/pool.py", line 873, in next
    raise value
OSError: File error: Invalid input file /home/juliana/Downloads/Ache/compounds/inactive_conf.sdf
Process Process-1:
Traceback (most recent call last):
  File "/home/juliana/anaconda3/envs/psearch/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/juliana/anaconda3/envs/psearch/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/juliana/anaconda3/envs/psearch/lib/python3.12/site-packages/psearch/prepare_dataset.py", line 61, in common
    create_db.main_params(dbout_fname=filenames[4],
  File "/home/juliana/anaconda3/envs/psearch/lib/python3.12/site-packages/psearch/scripts/create_db.py", line 156, in main_params
    for i, res in enumerate(p.imap_unordered(map_process_mol,
  File "/home/juliana/anaconda3/envs/psearch/lib/python3.12/multiprocessing/pool.py", line 451, in <genexpr>
    return (item for chunk in result for item in chunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/juliana/anaconda3/envs/psearch/lib/python3.12/multiprocessing/pool.py", line 873, in next
    raise value
OSError: File error: Invalid input file /home/juliana/Downloads/Ache/compounds/active_conf.sdf
  File "/home/juliana/anaconda3/envs/psearch/lib/python3.12/site-packages/psearch/prepare_dataset.py", line 61, in common
    create_db.main_params(dbout_fname=filenames[4],
  File "/home/juliana/anaconda3/envs/psearch/lib/python3.12/site-packages/psearch/scripts/create_db.py", line 156, in main_params
    for i, res in enumerate(p.imap_unordered(map_process_mol,
  File "/home/juliana/anaconda3/envs/psearch/lib/python3.12/multiprocessing/pool.py", line 451, in <genexpr>
    return (item for chunk in result for item in chunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/juliana/anaconda3/envs/psearch/lib/python3.12/multiprocessing/pool.py", line 873, in next
    raise value
OSError: File error: Invalid input file /home/juliana/Downloads/Ache/compounds/inactive_conf.sdf
Process Process-1:
Traceback (most recent call last):
  File "/home/juliana/anaconda3/envs/psearch/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/juliana/anaconda3/envs/psearch/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/juliana/anaconda3/envs/psearch/lib/python3.12/site-packages/psearch/prepare_dataset.py", line 61, in common
    create_db.main_params(dbout_fname=filenames[4],
  File "/home/juliana/anaconda3/envs/psearch/lib/python3.12/site-packages/psearch/scripts/create_db.py", line 156, in main_params
    for i, res in enumerate(p.imap_unordered(map_process_mol,
  File "/home/juliana/anaconda3/envs/psearch/lib/python3.12/multiprocessing/pool.py", line 451, in <genexpr>
    return (item for chunk in result for item in chunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/juliana/anaconda3/envs/psearch/lib/python3.12/multiprocessing/pool.py", line 873, in next
    raise value
OSError: File error: Invalid input file /home/juliana/Downloads/Ache/compounds/active_conf.sdf**

No file in the "compounds" folder was generated... Any suggestions on how to move forward?

Thanks in advance...

Juliana

**Comment by DrrDom** [comment]
From which branch did you install psearch? You have to use `gen_pharms` branch, it is the most recent. Unfortunately we still did not fix all remaining bugs and merge it to the master.
Another aspect, I never used psearch with python 3.12, maximum it was 3.9. However, it should be a problem.

**Comment by julianaamorim** [comment]
Thank you for your guidance, @DrrDom. I had indeed cloned the master branch. I was able to move forward by reproducing the ck8 dataset and I also want to use AChE, P450 3A4 and A2a to understand the program well... 
 Your program was an incredible find, great job!

**Comment by julianaamorim** [comment]
Thanks

**Comment by julianaamorim** [comment]
Thank you for your guidance, @DrrDom. I had indeed cloned the master branch. I was able to move forward by reproducing the results with ck8 dataset. Your program was an incredible find, congratulations!

**Comment by julianaamorim** [comment]
Running psearch on my current working dataset got my trainset list stuck... I tried some checking in select_training_set_rdkit.py to understand the problem, but to no avail...

**>> psearch -p my_models_2/created_pharmacophores/ -i beta_2_short.smi -d dbs/beta.dat -c 4
Size of df before generating fingerprints: (101, 3)
Size of df after generating fingerprints: (101, 4)
Size of df_mols before concatenation: (101, 4)
Size of df_mols after concatenation: (101, 5)
100 molecules screened 00:00:01
external_statistics.txt: (0.009s)**

Any light?

**Comment by DrrDom** [comment]
Does it return any pharmacophore model? If not, it may happen that it cannot create training sets. I got something similar in the past and it would be reasonable to implement another modeling mode, where all input ligands will be taken as a training set without selection like now. It may also be some bug. If you can share your data set, I may look on it when I'll have time, but I do not promise that will do this quickly.

**Comment by julianaamorim** [comment]
No model is returned, but the _cluster_stat_trh0.4.txt_ is generated... When and if you have time, I'd be very grateful...

**smi file**
smiles	mol_id	activity
[H][N+](CCC(=O)N([H])Cc1ccccc1)=[N+]([H])C(=O)c2ccncc2	C1	1
O=C2C(/C=C(/N[S](=O)(=O)c1ccc(C)cc1)c3ccccc23)[S]/C4=N/C=NN4[H]	Z4041	1
O=[S](=O)(N=C1C=CC(=O)c2ccccc12)c3ccc(cc3)C(C)(C)C	Z7145	1
O=C(/C=C/c1cc(O[H])c(cc1)O[H])OCC	Z5317238	1
Cc3ccc2Oc1ccccc1[N+]([H])=C(c2c3)N4CC[N+]([H])([H])CC4	ZINC000000000931 	
O=C(N([H])N([H])Cc1ccccc1)c2cc(C)on2	ZINC000000001587	1
[F]C([F])([F])c2cccc1c(cc(nc12)C([F])([F])[F])[C@@]([H])(O[H])[C@@]3([H])CCCC[N+]3([H])[H]	ZINC000000537964	1
[H]N(CCC(=O)N([H])Cc1ccccc1)N([H])C(=O)c2ccncc2	ZINC000001713761	1
[H][N+](CCc1ccccc1)=[N+]([H])[H]	ZINC000019166991	1
O=C([N+]([H])=[N+]([H])Cc1ccccc1)c2ccco2	C2	1
[H]N2c1ccccc1CN(CCCOC)C2[S]CC(=O)N([H])c3cc(ccc3OC)OC	C10	1
[H]N(c1cc(C)nc2ccccc12)c3ccc(cc3)C(C)=O	C13	1
O=C(c1ccc(cc1)OCc2ccccc2)[N+]([H])=[N+]([H])[H]	C16	1
O=C([N+]([H])=[N+]([H])CCC#N)c1ccccc1	C18	1
O=C(/C=C/c1cc(OC)c(O[H])c(c1)OC)OCCCC	C34	1
[H]Oc1cc(O[H])c(cc1c3nc2ccccc2[s]3)O[H]	C40	1
O=C2c1ccccc1N=C(N2[H])c3ccc(cc3)OC	C45	1
C[C@]34CC[C@]2([H])c1ccc(cc1CC[C@@]2([H])[C@]3([H])CC[C@]4([H])O[H])O[H]	Z_Estradiol	1
[H]Oc1ccc(cc1c2cc(ccc2O[H])CC=C)CC=C	Z_Magnolol	1
[F]C([F])([F])c4cc3N(CCC[N+]1([H])CC[N+](C)([H])CC1)c2ccccc2[S]c3cc4	Z_trifluoperazine	1
c1cc2c(cc1/C=C/CO)O[C@H]([C@@H](O2)c1ccc2c(c1)O[C@@H]([C@H](O2)c1ccc(c(c1)O)O)CO)CO	CHEMBL4633555	1
CNc1c2c(c3c4c(c(nnn4)N4CC[NH2+]CC4)sc3n1)CCCC2	CHEMBL4636276	1
c1cc(nc2c1c1c(s2)c(nc(n1)Cl)N1CC[NH2+]CC1)N1CCOCC1	CHEMBL4638468	1
c1cc2c(cc1/C=C/CO)O[C@@H]([C@H](O2)CO)c1ccc2c(c1)O[C@H]([C@@H](O2)CO)c1ccc(c(c1)O)O	CHEMBL4640728	1
C[C@@]12CC[C@H]3[C@]([C@H](C[C@H]([C@@]3([C@H]1CC=C1[C@]2(CC[C@]2([C@H]1CC(CC2)(C)C)C(=O)[O-])C)C)O)O)(C)CO	CHEMBL4641100	1
CO[C@@]1(C(=O)CCO1)CO	CHEMBL4641934	1
c1cc(nc2c1c1c(s2)c(ncn1)N1CC[NH2+]CC1)N1CCOCC1	CHEMBL4642130	1
CC(=O)N[C@@H]1[C@H]([NH2+][C@H]([C@H]([C@@H]1O)O)CO)Cc1ccccc1	CHEMBL4643490	1
[C@H]1([C@H](C(=O)O[C@@H]1[C@@H](C(=O)[O-])O)O)O	CHEMBL4649498	1
O=C(OC)N([H])c3nc2[s]c1CCCCc1c2[s]3	C00191122	0
C[C@@]([H])([C@]([H])(C/C1=C(\C)C(=NN1C)CC)N([H])N([H])[H])[S](=O)(=O)C	C97750762	0
CN(C)c1ccc(cc1)[C@@]([H])(C/C2=N/C=NN2CCC)[N+]([H])=[N+]([H])[H]	C97754767	0
[H]/[N+](=[N+](/[H])[H])[C@]([H])(C/C1=N/C=NN1CCC)c3ccc2cocc2c3	C97754821	0
Cc1cc(cnc1)[C@@]([H])(C2=C(C)C=NN2CC[N+](C)(C)[H])N([H])N([H])[H]	C97783701	0
Cc2ccc1oc(cc1c2)[C@@]([H])(N([H])N([H])[H])[C@]3([H])CC[C@@](C)([H])O3	C97788679	0
O=C1C(C)=C(C=NN1CCO[H])N([H])CC2(CC2)CCO[H]	C97818797	0
C[C@@]2([H])CCc1cc(ccc1N2[H])N(C)C[C@]3(CCC3)[N+](C)(C)[H]	C97928488	0
O=C2c1ccccc1O/C=C2/CNO[H].[B]	C98095368	0
O=C(CCCCCN2C(=O)c1ccccc1C2=O)N([H])C[C@]3([H])CCCN3C4[S]C=CN4[H]	C98301690	0
O=C(COc1ccccc1CC=C)N([H])c3[s]c2CC[C@@]([H])(c2c3C(=O)OC)C(=O)OC	C01284766	0
Cc1ccc(o1)C=2NN(CC=2CN(Cc3ccccc3)C(=O)CCC(=O)[O-])c4ccccc4	C02657839	0
COc1ccc(cc1COc2ccccc2OCC)C=NN3C(=NN([H])C3[S])C([F])([F])[H]	C02792505	0
[H]N(/C=C(/C#N)C(=O)C(=O)OCC)c1ccc(cc1)Oc2ncc(cc2C)C([F])([F])[F]	C03048568	0
O=C(c1ccc(cc1)OCC)[C@]2([H])C(=O)C(=O)N(CC[N+]([H])(CC)CC)[C@@]2([H])c3ccc(C)o3	C04312200	0
O=C(O[C@](C)([H])C(=O)N([H])CC/C1=C/CCCC1)C(=CC=2/C=C(/C)N(CCOC)C=2C)C#N	C04494325	0
COc2cccc(C[N+]([H])([H])CC[S]/C1=N/N=NN1C)c2OCc3ccc(C)cc3	C04998049	0
COc2cccc(C[N+]([H])([H])CC[S]/C1=N/N=NN1C)c2OCc3ccccc3C	C04998050	0
CN2N=Cc1c(ncnc12)N([H])C[C@]([H])(CC)CCCC	C06379574	0
[S]=C(N(Cc1ccc(OC)c(OC)c1OC)Cc2ccco2)N([H])C[C@]3([H])CCCO3	C06468676	0
[S]=C(N(Cc1ccc(OC)c(OC)c1OC)Cc2ccco2)N([H])C[C@@]3([H])CCCO3	C06468683	0
[H]N(Cc1ccccc1C([F])([F])[F])C2=NN=NN2CCCC	C06697327	0
O=C(CN2N=CC=3COc1ccc(C)cc1C2=3)N([H])CC[N@+]([H])(CCCC)Cc4ccco4	C06724370	0
C[C@@]([H])(OC(=O)c1cccnc1[S]C([F])([F])[H])C(=O)C2=C(C)C(=C(C)N2[H])C(=O)OC	C07284599	0
COc1cc(ccc1OCc2ccc([F])cc2)C[N+]([H])([H])CCC[S]/C3=N/N=NN3C	C07541460	0
C[C@]([H])(OC(=O)CCc1c(C)nc(nc1C)[S]C)C(=O)C2=C(C)C(=C(C)N2[H])C(=O)C	C07866267	0
O=C(N([H])C1=NN=C([S]1)[S]CC[N+]([H])(CC)CC)[C@@]2([H])CC(=O)N(C2)c3ccc(C)cc3	C08906413	0
O=C(N([H])C1=NN=C([S]1)[S]CC[N+]([H])(CC)CC)[C@]2([H])CC(=O)N(C2)c3ccc(C)c(C)c3	C08909171	0
O=C(c1ccc(cc1)OC(C)(C)[H])[C@]2([H])C(=O)C(=O)N(CC[N+]([H])(CC)CC)[C@@]2([H])c3cccnc3	C08996686	0
Cc1ccc(cc1)C3=N/N=C(/[S]CC(=O)N(C)CC(=O)N([H])C2([H])CC2)N3CC=C	C10240380	0
O=C(COC(=O)[C@]([H])(CC)c1ccccc1)N([H])c2ccc(C)c(c2)[S](=O)(=O)N(C)C	C11412714	0
O=C(N([H])[C@]([H])(C(=O)OCC(C)(C)[H])C(C)(C)[H])c1cccc(c1)[S](=O)(=O)N(CC)CC	C11779585	0
C[N@+]([H])(Cc2cccc(O[C@](C)([H])CN([H])[S](=O)(=O)c1ccc(cc1)OC)c2)Cc3ccoc3	C11839981	0
COc1ccccc1/C3=C/N2C(=C[S]C2=N3)C(=O)N([H])[C@]([H])(CC[S]C)C(=O)OC	C11935863	0
C[N@+]([H])(C/C1=C/N=C(N1CCCC)[S](=O)(=O)CC)CC/C3=N/c2cc([F])ccc2N3[H]	C12301947	0
CN1C(=N/N=C1/[S]CCOc2ccc([F])cc2)[C@](C)([H])N([H])[S](=O)(=O)c3ccc[s]3	C12470383	0
O=C1C[C@@]([H])(CN1c2ccccc2[C@@](C)([H])CC)C(=O)N([H])c3nc(c[s]3)CC(=O)OCC	C12734782	0
C[C@]2(CC(=O)[C@]([H])(C(=O)OCC=C)[C@@]([H])(c1ccc(cc1)N(C)C)[C@@]2([H])C(=O)OCC=C)O[H]	C13138895	0
O=C(COc1ccccc1OCC)N([H])CCN2N=C(C=CC2=O)c3ccc(C)cc3	C13603357	0
[H][N@+]3(CCc1c([s]c(c1C(=O)OC)[S](=O)(=O)N([H])C[C@]2([H])CCCO2)C3)C([H])(CC)CC	C14951746	0
[H][N@@+]1(CCC[C@@](C1)(Cc2ccc([F])cc2[F])C(=O)OCC)CC=3CN([H])NC=3C(=O)OCC	C15080487	0
[H]N([H])c1ccc(nc1)OC[C@]2([H])CCCCO2	C19281680	0
[H][N@+](Cc1cccc(OC)c1OC)(Cc2ccccn2)CC=3NN=NC=3c4ccccc4	C19567538	0
[H]N1C(=NC2=C1C=NN2C(C)(C)[H])c3[s]ccc3C	C19792852	0
Cc1cc(cc(c1C)[C@]([H])([N+]([H])([H])[H])C(C)(C)[H])N(=O)=O	C19970419	0
[H][N+]([H])(CCC[N+]1([H])CCCCC1)[C@@](C)([H])c2cccc(c2)N(=O)=O	C20128893	0
[H][N+]1(CC[N@+]([H])(CC1)Cc3ccc2OCOc2c3)C[C@@]([H])(O[H])COc4ccc(cc4OC)CC=C	C20347390	0
C/C1=C/C(=NN1CCCC)N([H])C/C2=C/C=NN2CCC	C20351026	0
CN1C=C(/C=C1/C(=O)N([H])CC[N+]([H])(CCC)CCC)[S](=O)(=O)N2CCc3ccccc23	C20487913	0
[H][N+]([H])(C/C1=C/C=CN1/C2=N/N=C([S]2)N3CCCC3)CCc4ccc(OC)c(c4)OC	C20576497	0
O=C(N([H])CCC[N+]1([H])CC[N@+]([H])(CC1)CCC)C2=C(C)NN(C2N3C=CC=C3)c4cccc(C)c4	C20979391	0
CC1(C)[C@]([H])(C=C(C)C)[C@]1([H])C(=O)N([H])C2=NN=C[S]2	C21215995	0
O=C(COC(=O)Cc1ccc(cc1)OC([F])([F])[H])N([H])c2ccc(cc2)C[N+]3([H])CCOCC3	C21912133	0
COc1cc(ccc1OC/C2=N/N=NN2c3ccc(C)cc3)C[N+]([H])([H])Cc4ccc([F])cc4	C22108260	0
[H][N+]1(CC[N@+]([H])(CC1)Cc3ccc2OCOc2c3)C[C@]([H])(O[H])COCCOc4ccc(cc4)CC	C22916649	0
[H][N+]3(CC[N+]([H])(CCC/C1=N/C(=NO1)c2cccc(c2)C([F])([F])[F])CC3)CC(=O)N([H])CC=C	C23057372	0
O=C(c1cc(ccc1N2CCOCC2)[S](=O)(=O)N(CC)CC)N([H])[C@](C)([H])CCC	C23224208	0
[F]c1ccc(cc1C(=O)N([H])C2=NN=C([S]2)C([H])(CC)CC)[S](=O)(=O)N(CC)CC	C23650792	0
O=C(N([H])c1ccc(cc1)[S](=O)(=O)N(CC)CC)C(=CC=2/C=C(/C)N(CCC)C=2C)C#N	C24006636	0
O=C(CC[N@@+]([H])(Cc1ccc[s]1)[C@@]2([H])CC2)N([H])c3[s]c(c(C)c3C(=O)OC)C(=O)OC	C24774316	0
[H]N2c1cc(ccc1N(CCC)C2CCC(=O)N([H])[C@](C)([H])CC)[S](=O)(=O)N(CC)CC	C27337732	0
O=C(CCCN3c1cc([F])ccc1N2C=CC=C2C3=O)N([H])CCC[N+]4([H])CC[N+]([H])(CC4)CC	C33031766	0
O=C(CN2c1ccccc1N(CC)C(=O)C2=O)N([H])CC[N@@+]([H])(Cc3ccc[s]3)[C@](C)([H])CC	C33068502	0
O=C(N([H])Cc1ccccc1OCC)[C@@]([H])(CC)OC=2C=CC(=O)N(N=2)c3ccc([F])cc3	C33124788	0
O=C1N(CCC[N+]([H])(CC)CC)C(=C(C1=O)C(=O)c2cccc(c2)OCC)c3ccc(C)o3	C33723426	0
[H][N@@+]3(CC=1OC=C(N=1)C(=O)N(CC)[C@@]2([H])CCCCC2)CC[N+]([H])(CC3)C[C@]([H])(O[H])CCC=C	C34677841	0
O=C1C(=O)C(=C(N1CC[N+](C)(C)[H])c2ccc(C)o2)C(=O)c3cccc(c3)OCCC	C35295901	0
O=C2Cc1cc(c(cc1N2[H])O[C@@]3([H])CCCC[C@@]3(C)[H])N([H])[H]	C35345705	0
O=C2CCc1cc(c(cc1N2[H])O[C@@]3([H])CCC[C@](C)([H])C3)N([H])[H]	C35356208	0
C[C@@]([H])(C(=O)C=1C(C)=C(N([H])C=1C)C(=O)OC)N(CC=C)[S](=O)(=O)c2ccc(C)cc2	C36004504	0
C[C@]1([H])C[N+]([H])(C[C@](C)([H])O1)[C@]([H])(C(=O)N([H])[H])C(C)(C)[H]	C36092632	0

**cluster_stat_trh0.4.txt**
#The file contains statistical information about the cluster 
#and the index of the molecule according to its location in the input file 

cluster 0, cluster length 4, share of active 0.0
35,49,85,87

cluster 1, cluster length 3, share of active 0.0
90,44,46

cluster 2, cluster length 2, share of active 0.0
89,88

cluster 3, cluster length 2, share of active 0.0
77,52

cluster 4, cluster length 2, share of active 0.0
75,67

cluster 5, cluster length 2, share of active 0.0
48,47

cluster 6, cluster length 2, share of active 0.0
41,40

cluster 7, cluster length 2, share of active 0.0
38,37

cluster 8, cluster length 2, share of active 0.0
24,23

cluster 9, cluster length 1, share of active 0.0
100

cluster 10, cluster length 1, share of active 0.0
99

cluster 11, cluster length 1, share of active 0.0
98

cluster 12, cluster length 1, share of active 0.0
97

cluster 13, cluster length 1, share of active 0.0
96

cluster 14, cluster length 1, share of active 0.0
95

cluster 15, cluster length 1, share of active 0.0
94

cluster 16, cluster length 1, share of active 0.0
93

cluster 17, cluster length 1, share of active 0.0
92

cluster 18, cluster length 1, share of active 0.0
91

cluster 19, cluster length 1, share of active 0.0
86

cluster 20, cluster length 1, share of active 0.0
84

cluster 21, cluster length 1, share of active 0.0
83

cluster 22, cluster length 1, share of active 0.0
82

cluster 23, cluster length 1, share of active 0.0
81

cluster 24, cluster length 1, share of active 0.0
80

cluster 25, cluster length 1, share of active 0.0
79

cluster 26, cluster length 1, share of active 0.0
78

cluster 27, cluster length 1, share of active 0.0
76

cluster 28, cluster length 1, share of active 0.0
74

cluster 29, cluster length 1, share of active 0.0
73

cluster 30, cluster length 1, share of active 0.0
72

cluster 31, cluster length 1, share of active 0.0
71

cluster 32, cluster length 1, share of active 0.0
70

cluster 33, cluster length 1, share of active 0.0
69

cluster 34, cluster length 1, share of active 0.0
68

cluster 35, cluster length 1, share of active 0.0
66

cluster 36, cluster length 1, share of active 0.0
65

cluster 37, cluster length 1, share of active 0.0
64

cluster 38, cluster length 1, share of active 0.0
63

cluster 39, cluster length 1, share of active 0.0
62

cluster 40, cluster length 1, share of active 0.0
61

cluster 41, cluster length 1, share of active 0.0
60

cluster 42, cluster length 1, share of active 0.0
59

cluster 43, cluster length 1, share of active 0.0
58

cluster 44, cluster length 1, share of active 0.0
57

cluster 45, cluster length 1, share of active 0.0
56

cluster 46, cluster length 1, share of active 0.0
55

cluster 47, cluster length 1, share of active 0.0
54

cluster 48, cluster length 1, share of active 0.0
53

cluster 49, cluster length 1, share of active 0.0
51

cluster 50, cluster length 1, share of active 0.0
50

cluster 51, cluster length 1, share of active 0.0
45

cluster 52, cluster length 1, share of active 0.0
43

cluster 53, cluster length 1, share of active 0.0
42

cluster 54, cluster length 1, share of active 0.0
39

cluster 55, cluster length 1, share of active 0.0
36

cluster 56, cluster length 1, share of active 0.0
34

cluster 57, cluster length 1, share of active 0.0
33

cluster 58, cluster length 1, share of active 0.0
32

cluster 59, cluster length 1, share of active 0.0
31

cluster 60, cluster length 1, share of active 0.0
30

cluster 61, cluster length 1, share of active 0.0
29

cluster 62, cluster length 1, share of active 0.0
28

cluster 63, cluster length 1, share of active 0.0
27

cluster 64, cluster length 1, share of active 0.0
26

cluster 65, cluster length 1, share of active 0.0
25

cluster 66, cluster length 1, share of active 0.0
22

cluster 67, cluster length 1, share of active 0.0
21

cluster 68, cluster length 1, share of active 1.0
20

cluster 69, cluster length 1, share of active 1.0
19

cluster 70, cluster length 1, share of active 1.0
18

cluster 71, cluster length 1, share of active 1.0
17

cluster 72, cluster length 1, share of active 1.0
16

cluster 73, cluster length 1, share of active 1.0
15

cluster 74, cluster length 1, share of active 1.0
14

cluster 75, cluster length 1, share of active 1.0
13

cluster 76, cluster length 1, share of active 1.0
12

cluster 77, cluster length 1, share of active 1.0
11

cluster 78, cluster length 1, share of active 1.0
10

cluster 79, cluster length 1, share of active 1.0
9

cluster 80, cluster length 1, share of active 1.0
8

cluster 81, cluster length 1, share of active 1.0
7

cluster 82, cluster length 1, share of active 1.0
6

cluster 83, cluster length 1, share of active 1.0
5

cluster 84, cluster length 1, share of active 1.0
4

cluster 85, cluster length 1, share of active 1.0
3

cluster 86, cluster length 1, share of active 1.0
2

cluster 87, cluster length 1, share of active 1.0
1

**Comment by julianaamorim** [comment]
Increasing the number of active compounds solved the problem...
